spring:
  profiles:
    active: docker
---
spring:
  profiles: cloud
  cloud:
    config:
      enabled: true
server:
  port: 9004
neo4j:
  uri: http://ec2-52-10-122-143.us-west-2.compute.amazonaws.com:7474/db/data/
  username: neo4j
  password: graphdb
  bootstrap: false
aws:
  s3:
    url: https://s3.amazonaws.com/dataset-demos
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true
---
spring:
  profiles: docker
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:./.h4/testdb
server:
    port: 9006
#neo4j:
#  uri: http://localhost:7474/db/data/
#  username: neo4j
#  password: graphdb
#  bootstrap: true
aws:
  s3:
    url: http://localhost:9006
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true